apiVersion: v1
kind: Service
metadata:
  name: mars-app-service
  labels:
    name:  mars-app-service
    app: mars-app
spec:
  type: LoadBalancer
  selector:
    name: mars-app-pod
    app: mars-app
  ports:
  - port: 80
    targetPort: 80
